Code/SourceCode/QLQ.FEW/Controllers/SoTheoDoiController.cs
using FX.Core;
using log4net;
using QLQ.Core.CustomView;
using QLQ.Core.IService;
using System.Collections.Generic;
using System.Web.Mvc;
using QLQ.Core.StoreProcedure;
using System.Linq;
using QLQ.FEW.Helper;
using QLQ.Core.Security;

namespace QLQ.FEW.Controllers
{
    [Function(QlqFunctions.SOTHEODOI)]
    [Authorize]
    public class SoTheoDoiController : BaseController
    {
        private readonly IDM_NGANHANGService _iDmNganHangService;
        private readonly ILAISUATNH_DTLService _iLaiSuatNhDtlService;
        private readonly ILAISUATNH_HDRService _iLaiSuatNhHdrService;
        private static readonly ILog Log = LogManager.GetLogger(typeof(SoTheoDoiController));
        private readonly QLQStoreProcedure _spQlq = new QLQStoreProcedure();
        //
        // GET: /SoTheoDoi/
        public SoTheoDoiController()
        {
            _iDmNganHangService = IoC.Resolve<IDM_NGANHANGService>();
            _iLaiSuatNhDtlService = IoC.Resolve<ILAISUATNH_DTLService>();
            _iLaiSuatNhHdrService = IoC.Resolve<ILAISUATNH_HDRService>();
        }

        [ActionPermissions(QlqActions.VIEW)]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SoTheoDoiPartial()
        {
            ViewBag.ListNganHang = _iDmNganHangService.GetAll();
            return PartialView("SoTheoDoiPartial");
        }

        [HttpPost]
        [ActionPermissions(QlqActions.VIEW)]
        public ActionResult fn_InAn(long? nganHang, int year, int cnTc, int type)
        {
            List<record_SoTheoDoi> records = new List<record_SoTheoDoi>();
            if (cnTc == 0 && type == 0)
                records = _spQlq.sp_SoTheoDoi(nganHang, year, (int)ELoaiLaiSuat.CaNhanKyCuoi);//cuối kì cá nhân
            else if (cnTc == 0 && type == 1)
                records = _spQlq.sp_SoTheoDoi(nganHang, year, (int)ELoaiLaiSuat.CaNhanHangThang);//hàng tháng cá nhân
            else if (cnTc == 1 && type == 0)                
                records = _spQlq.sp_SoTheoDoi(nganHang, year, (int)ELoaiLaiSuat.ToChucKyCuoi);//cuối kì tổ chức
            else
                records = _spQlq.sp_SoTheoDoi(nganHang, year, (int)ELoaiLaiSuat.ToChucHangThang);//hàng tháng tổ chức
            List<SotheoDoiModel> lst = new List<SotheoDoiModel>();
            SotheoDoiModel model = new SotheoDoiModel();
            decimal id = 0;
            if (records.Count > 0) id = records[0].LaiSuatId;//nếu có dữ liệu trả về thì gán id vào để check
            LaiSuatNHModel lsHuyDong = new LaiSuatNHModel();

            foreach (var item in records)
            {
                if (id == item.LaiSuatId)
                {
                    //gán các trường vào model
                    setSoTheoDoiDetail(ref model, item, lsHuyDong);
                }
                if (id != item.LaiSuatId)
                {
                    // add the old to list
                    lst.Add(model);
                    id = item.LaiSuatId;
                    // khoi tao cai moi
                    model = new SotheoDoiModel();
                    setSoTheoDoiDetail(ref model, item, lsHuyDong);
                }
            }

            if (id > 0)
                lst.Add(model);
            lst = lst.OrderBy(t => t.NGAY_HIEULUC).ToList();
            SoTheoDoi_Report report = new SoTheoDoi_Report();
            report.DataSource = lst;
            report.txt_nam.Text = year.ToString();
            report.txt_name.Text = _iDmNganHangService.GetById(nganHang).TEN_NGANHANG;
            return PartialView("ReportSoTheoDoi", report);
        }

        [ActionPermissions(QlqActions.VIEW)]
        private void setSoTheoDoiDetail(ref SotheoDoiModel model, record_SoTheoDoi item, LaiSuatNHModel lsHuyDong)
        {
            model.NGAY_HIEULUC = item.NGAY_HIEULUC;
            model.SO_CVDEN = item.SO_CVDEN;
            model.NGAY_CVDEN = item.NGAY_CVDEN;
            model.SO_CVNH = item.SO_CVNH;
            model.NGAY_CVNH = item.NGAY_CVNH;
            model.THONGBAO_NH = item.THONGBAO_NH;
            model.NGAY_THONGBAO = item.NGAY_THONGBAO;
            long? so_thang = lsHuyDong.getSoThang(item.KYHAN_ID);
            if (so_thang == null)
                so_thang = 0;
            if (so_thang == -1) model.KKH = item.Value;
            else if (so_thang == 0) model.Under1Month = item.Value;
            else if (so_thang == 1) model.Month1 = item.Value;
            else if (so_thang == 2) model.Month2 = item.Value;
            else if (so_thang == 3) model.Month3 = item.Value;
            else if (so_thang == 4) model.Month4 = item.Value;
            else if (so_thang == 5) model.Month5 = item.Value;
            else if (so_thang == 6) model.Month6 = item.Value;
            else if (so_thang == 7) model.Month7 = item.Value;
            else if (so_thang == 8) model.Month8 = item.Value;
            else if (so_thang == 9) model.Month9 = item.Value;
            else if (so_thang == 10) model.Month10 = item.Value;
            else if (so_thang == 11) model.Month11 = item.Value;
            else if (so_thang == 12) model.Month12 = item.Value;
            else if (so_thang == 18) model.Month18 = item.Value;
            else if (so_thang == 24) model.Month24 = item.Value;
            else if (so_thang == 36) model.Month36 = item.Value;
            else if (so_thang == 60) model.Month60 = item.Value;
        }
    }
}

Code/SourceCode/QLQ.FEW/Views/SoTheoDoi/HeadResourcesPartial.cshtml
@Html.DevExpress().GetStyleSheets(
    new StyleSheet { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
    new StyleSheet { ExtensionSuite = ExtensionSuite.GridView },
    new StyleSheet() { ExtensionSuite = ExtensionSuite.Report }
   
)
@Html.DevExpress().GetScripts(
        //new Script { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
        ////new Script { ExtensionSuite = ExtensionSuite.HtmlEditor },
        //new Script { ExtensionSuite = ExtensionSuite.GridView }
)

Code/SourceCode/QLQ.FEW/Views/SoTheoDoi/Index.cshtml
@model QLQ.Core.CustomView.SotheoDoiModel

@{
    ViewBag.Title = "Số theo dõi lãi suất ngân hàng";
    Layout = "~/Views/Shared/_mainLayout.cshtml";
}

@section HeadResources{
    @Html.Partial("HeadResourcesPartial")
}
<script>
    function btn_InAnClick() {
        var NganHang = cbb_NganHang.GetValue();
        var ThoiGian = date_HieuLuc.GetValue();
        var loai = cbb_loaiLS.GetValue();
        var type = cbb_type.GetValue();
        LoadingPanel.Show();
        $.ajax({
            type: "POST",
            url: '@Url.Action("fn_InAn", "SoTheoDoi")',
            data: {
                nganHang: NganHang,
                year: ThoiGian,
                cnTc: loai,
                type: type
            }
        }).done(function (result) {
            LoadingPanel.Hide();
            $("#SoTheoDoi_Report").html(result);
        });
    }
</script>
<div id="gridview" style="width:60%; margin:auto;">
    @Html.Action("SoTheoDoiPartial")
</div>
@Html.Partial("_Message")
@Html.Partial("_MessageSuccess")
@Html.Partial("LoadingPanel")
<div id="SoTheoDoi_Report"></div>

Code/SourceCode/QLQ.FEW/Views/SoTheoDoi/ReportSoTheoDoi.cshtml
<style type="text/css">
    .dx-overlay-wrapper {
        z-index: 100000 !important;
    }
</style>
<script type="text/javascript">
    function OnInit(s, e) {
        //var nodeKey = window.TreeList_NhomICD.GetFocusedNodeKey();
        //  window.popupReport19.PerformCallback();
        AdjustSize();
        ASPxClientUtils.AttachEventToElement(window, "resize", function (evt) {
            AdjustSize();
        });
    }
    function OnEndCallback(s, e) {
        AdjustSize();
    }
    function AdjustSize() {
        window.MauS12_H_Report.SetWidth(document.documentElement.clientWidth);
        window.MauS12_H_Report.SetHeight(document.documentElement.clientHeight);

    }
</script>
@model DevExpress.XtraReports.UI.XtraReport
@*// chỉ cần khai báo lớp cha*@
@Html.DevExpress().PopupControl(
    settings =>
    {
        settings.Name = "SoTheoDoiReport";
        settings.ClientSideEvents.PopUp = "function(s, e) { s.SetWidth(document.documentElement.clientWidth); s.SetHeight(document.documentElement.clientHeight); }";
        settings.ShowOnPageLoad = true;
        settings.AllowDragging = false;
        settings.CloseAction = CloseAction.CloseButton;
        settings.CloseOnEscape = true;
        settings.PopupAnimationType = AnimationType.None;
        settings.ShowHeader = true;
        settings.Modal = true;
        settings.ScrollBars = System.Web.UI.WebControls.ScrollBars.Auto;
        settings.HeaderText = "Số theo dõi";
        settings.ShowCloseButton = true;
        settings.PopupHorizontalAlign = PopupHorizontalAlign.LeftSides;
        settings.PopupVerticalAlign = PopupVerticalAlign.TopSides;
        settings.SetContent(() =>
        {
            @Html.DevExpress().WebDocumentViewer(poper => //khai báo đối tượng nặc danh sử dụng luôn
                        {

                            poper.Name = "Sotheodoi";


                        }).Bind(Model).GetHtml();
        });
    }).GetHtml()

Code/SourceCode/QLQ.FEW/Views/SoTheoDoi/SoTheoDoiPartial.cshtml
@Html.DevExpress().PopupControl(
    settings =>
    {
        settings.Name = "ModalSoTheoDoi";
        settings.Width = 530;
        settings.HeaderText = "Sổ theo dõi lãi suất ngân hàng";
        settings.Modal = true;
        settings.ShowCloseButton = false;
        settings.AllowDragging = false;
        settings.CloseAction = CloseAction.None;
        settings.ShowOnPageLoad = true;
        settings.PopupHorizontalAlign = PopupHorizontalAlign.WindowCenter;
        settings.PopupVerticalAlign = PopupVerticalAlign.WindowCenter;

        settings.SetContent(() =>
        {
            ViewContext.Writer.Write("<table style='margin:20px;'><tr><td style='line-height:25px; padding-left:20px; width:100px;'><b>Ngân hàng:</b></td><td>");
            Html.DevExpress().ComboBox(cb =>
            {
                cb.Name = "cbb_NganHang";
                cb.Width = 150;
                cb.SelectedIndex = 0;
                cb.Properties.IncrementalFilteringMode = IncrementalFilteringMode.StartsWith;
                cb.Properties.DropDownStyle = DropDownStyle.DropDown;
                cb.Properties.TextField = "TEN_NGANHANG";
                cb.Properties.ValueField = "NGANHANG_ID";
            }).BindList(ViewBag.ListNganHang).GetHtml();

            ViewContext.Writer.Write("</td><td></td></tr><tr><td style='line-height:25px; padding-left:20px; '><b>Thời gian:</b></td><td>");
            Html.DevExpress().ComboBox(cb =>
            {
                cb.Name = "date_HieuLuc";
                cb.Width = 150;
                cb.SelectedIndex = 0;
                cb.Properties.IncrementalFilteringMode = IncrementalFilteringMode.StartsWith;
                cb.Properties.DropDownStyle = DropDownStyle.DropDown;
                int i;
                for (i = DateTime.Now.Year; i >= 2000; i--)
                {
                    cb.Properties.Items.Add(i.ToString(),i);
                }
            }).GetHtml();
            ViewContext.Writer.Write("</td><td></td></tr><tr><td style='line-height:25px; padding-left:20px;'><b>Loại lãi suất:</b></td><td>");
            Html.DevExpress().ComboBox(cb =>
            {
                cb.Name = "cbb_loaiLS";
                cb.Width = 150;
                cb.SelectedIndex = 0;
                cb.Properties.IncrementalFilteringMode = IncrementalFilteringMode.StartsWith;
                cb.Properties.DropDownStyle = DropDownStyle.DropDown;
                cb.Properties.Items.Add("Lãi suất cá nhân",0);
                cb.Properties.Items.Add("Lãi suất tổ chức",1);
            }).GetHtml();

            ViewContext.Writer.Write("</td><td style='padding-left:20px;'>");

            Html.DevExpress().ComboBox(cb =>
            {
                cb.Name = "cbb_type";
                cb.Width = 150;
                cb.SelectedIndex = 0;
                cb.Properties.IncrementalFilteringMode = IncrementalFilteringMode.StartsWith;
                cb.Properties.DropDownStyle = DropDownStyle.DropDown;
                cb.Properties.Items.Add("Lãi suất cuối kì",0);
                cb.Properties.Items.Add("Lãi suất hàng tháng",1);
            }).GetHtml();

            ViewContext.Writer.Write("</td></tr><tr><td colspan='3' style='text-align:center; padding-top:15px;'>");
            Html.DevExpress().Button(
                buttonSettings =>
                {
                    buttonSettings.Name = "btn_InAn";
                    buttonSettings.ControlStyle.CssClass = "button";
                    buttonSettings.Width = 100;
                    buttonSettings.Text = "In ấn";
                    buttonSettings.UseSubmitBehavior = true;
                    buttonSettings.ClientSideEvents.Click = "btn_InAnClick";
                }
            )
            .Render();
            ViewContext.Writer.Write(" &nbsp; &nbsp;");
            Html.DevExpress().Button(
                    buttonSettings =>
                    {
                        buttonSettings.Name = "btnCancel";
                        buttonSettings.ControlStyle.CssClass = "button";
                        buttonSettings.Width = 80;
                        buttonSettings.Text = "Hủy";
                        buttonSettings.ClientSideEvents.Click = "function(s, e){ window.location.href='/' }";
                    }
                )
                .Render();
            ViewContext.Writer.Write("</td></tr></table>");
        });
    }).GetHtml()