Code/SourceCode/QLQ.FEW/Controllers/HOSOController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using QLQ.Core.IService;
using FX.Core;
using QLQ.Core.Domain;
using log4net;
using DevExpress.Web;
using DevExpress.Web.Mvc;
using QLQ.Core.Common;
using QLQ.Core.Security;

namespace QLQ.FEW.Controllers
{
    [Function(QlqFunctions.HOSO)]
    [Authorize]
    public class HOSOController : BaseController
    {
        //
        // GET: /HOSO/
        public const string UploadDirectory = @"/Uploads/HoSo/";

        private readonly IHOSOService _iHoSoSvc;
        private readonly IDM_NGANHANGService _iDmNganHangSvc;

        public HOSOController()
        {
            _iHoSoSvc = IoC.Resolve<IHOSOService>();
            _iDmNganHangSvc = IoC.Resolve<IDM_NGANHANGService>();
        }

        [ActionPermissions(QlqActions.VIEW)]
        public ActionResult Index()
        {
            return View();
        }

        //public ActionResult Search()
        //{
        //    var strTimKiem = Request.Params["timkiemS"] ?? "";
        //    ViewData["DM_NGANHANG"] = _iDmNganHangSvc.Query.ToList();
        //    var dmKH = _iHoSoSvc.Search(strTimKiem);
        //    return PartialView("HOSOPartial", dmKH);
        //}


        public ActionResult HOSOPartial()
        {
            ViewData["DM_NGANHANG"] = _iDmNganHangSvc.Query.ToList();
            var dmKH = _iHoSoSvc.Query.Select(x => new { x.HOSO_ID, x.NGANHANG_ID, UPLOADS_DLNH = UploadDirectory + x.UPLOADS_DLNH, UPLOADS_GPKD = UploadDirectory + x.UPLOADS_GPKD, UPLOADS_GUQ = UploadDirectory + x.UPLOADS_GUQ, UPLOADS_BCTC = UploadDirectory + x.UPLOADS_BCTC });
            return PartialView("HOSOPartial", dmKH);
        }

        public ActionResult PopupSaveData()
        {
            ViewData["DM_NGANHANG"] = _iDmNganHangSvc.Query.ToList();
            return PartialView();
        }

        public ActionResult DragAndDropImageUpload_DLNH()
        {
            UploadedFile[] files = UploadControlExtension.GetUploadedFiles("ctrUpload_DLNH", UploadControlDemosHelper.ValidationSettings, uc_FileUploadComplete);
            return null;
        }

        public ActionResult DragAndDropImageUpload_GPKD()
        {
            UploadedFile[] files = UploadControlExtension.GetUploadedFiles("ctrUpload_GPKD", UploadControlDemosHelper.ValidationSettings, uc_FileUploadComplete);
            return null;
        }

        public ActionResult DragAndDropImageUpload_GUQ()
        {
            UploadedFile[] files = UploadControlExtension.GetUploadedFiles("ctrUpload_GUQ", UploadControlDemosHelper.ValidationSettings, uc_FileUploadComplete);
            return null;
        }

        public ActionResult DragAndDropImageUpload_BCTC()
        {
            UploadedFile[] files = UploadControlExtension.GetUploadedFiles("ctrUpload_BCTC", UploadControlDemosHelper.ValidationSettings, uc_FileUploadComplete);
            return null;
        }

        public void uc_FileUploadComplete(object sender, FileUploadCompleteEventArgs e)
        {
            if (e.UploadedFile.IsValid)
            {
                string resultFilePath = Request.MapPath(UploadDirectory + e.UploadedFile.FileName);

                try
                {
                    bool dirExist = System.IO.Directory.Exists(Server.MapPath(UploadDirectory));
                    if (!dirExist) // neu chua co thu muc
                    {
                        System.IO.Directory.CreateDirectory(UploadDirectory);
                    }

                    //Lưu file upload vào thư mục
                    e.UploadedFile.SaveAs(resultFilePath, true);
                    System.Web.UI.IUrlResolutionService urlResolver = sender as System.Web.UI.IUrlResolutionService;
                    if (urlResolver != null)
                    {
                        //e.CallbackData = urlResolver.ResolveClientUrl(resultFilePath);
                        e.CallbackData = UploadDirectory + e.UploadedFile.FileName;
                    }
                }
                catch (Exception ex) { }
            }
        }


        [ActionPermissions(QlqActions.DELETE)]
        public ActionResult DeletePartial(HOSO hoso)
        {
            try
            {
                _iHoSoSvc.Delete(hoso);
                _iHoSoSvc.CommitChanges();
                ViewData["EditSuccess"] = Resources.Localizing.MessageDelete;
            }
            catch (Exception ex)
            {
                ViewData["EditError"] = Resources.Localizing.MessageDate;
                //Log.Error("DeletePartial Xoa: " + ex.Message);
            }
            return HOSOPartial();
        }

        [ActionPermissions(QlqActions.EDIT)]
        public ActionResult LuuHoSo(HOSO hoso, string dlnh, string gpkd, string guq, string bctc)
        {
            hoso.UPLOADS_DLNH = dlnh;
            hoso.UPLOADS_GPKD = gpkd;
            hoso.UPLOADS_GUQ = guq;
            hoso.UPLOADS_BCTC = bctc;
            try
            {
                if (hoso.HOSO_ID == null)
                {
                    hoso.CREATION_DATE = DateTime.Now;
                    _iHoSoSvc.Clear();
                    _iHoSoSvc.CreateNew(hoso);
                }
                else
                {
                    var model = _iHoSoSvc.GetById(hoso.HOSO_ID);
                    if (model != null)
                    {
                        model.NGANHANG_ID = hoso.NGANHANG_ID;
                        model.UPLOADS_DLNH = hoso.UPLOADS_DLNH;
                        model.UPLOADS_GPKD = hoso.UPLOADS_GPKD;
                        model.UPLOADS_GUQ = hoso.UPLOADS_GUQ;
                        model.UPLOADS_BCTC = hoso.UPLOADS_BCTC;

                        model.LASTUPDATED_DATE = DateTime.Now;
                        _iHoSoSvc.Clear();
                        _iHoSoSvc.Update(model);
                    }
                    else
                    {
                        return Json("Fail", JsonRequestBehavior.AllowGet);
                    }
                }
                _iHoSoSvc.CommitChanges();
                return Json("Success", JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json("Fail", JsonRequestBehavior.AllowGet);
                //Log.Error("LuuHoSo: " + ex.Message);
            }
            return Json("Fail");
        }

        [ActionPermissions(QlqActions.EDIT)]
        public ActionResult SuaHoSo(long hosoId)
        {
            var hoso = _iHoSoSvc.GetById(hosoId);
            if (hoso == null)
            {
                return Json("Fail");
            }
            //set viewbag -> load image upload hidden
            ViewBag.UPLOADS_DLNH = hoso.UPLOADS_DLNH;
            ViewBag.UPLOADS_GPKD = hoso.UPLOADS_GPKD;
            ViewBag.UPLOADS_GUQ = hoso.UPLOADS_GUQ;
            ViewBag.UPLOADS_BCTC = hoso.UPLOADS_BCTC;

            hoso.UPLOADS_DLNH = UploadDirectory + hoso.UPLOADS_DLNH;
            hoso.UPLOADS_GPKD = UploadDirectory + hoso.UPLOADS_GPKD;
            hoso.UPLOADS_GUQ = UploadDirectory + hoso.UPLOADS_GUQ;
            hoso.UPLOADS_BCTC = UploadDirectory + hoso.UPLOADS_BCTC;

            ViewData["DM_NGANHANG"] = _iDmNganHangSvc.Query.ToList();
            return PartialView("PopupSaveData", hoso);
        }
    }
}

Code/SourceCode/QLQ.FEW/Views/HOSO/BCTCPartial.cshtml
@Html.DevExpress().Image(img =>
{
    img.Name = "UPLOADS_BCTC";
    img.Height = Unit.Pixel(100);

}).GetHtml()

Code/SourceCode/QLQ.FEW/Views/HOSO/DLNHPartial.cshtml
@Html.DevExpress().Image(imga =>
    {
        imga.Name = "UPLOADS_DLNH";
        imga.Height = Unit.Pixel(100);
    }).GetHtml()

Code/SourceCode/QLQ.FEW/Views/HOSO/FilterView.cshtml
@*<table style="width:98%">
    <tr>
        <td style="width:30%; padding-left:20px;">
            @Html.DevExpress().TokenBox(s =>
        {
            s.Properties.IncrementalFilteringMode = IncrementalFilteringMode.Contains;
            s.Name = "txtMA";
            s.Properties.NullText = "Nhập từ khóa tìm kiếm ...";
            s.ControlStyle.Font.Size = 13;
            //s.Properties.ClientSideEvents.KeyDown = "OnTextBoxKeyDown";
            s.Properties.DataSource = ViewData["List"];
            s.Properties.ShowDropDownOnFocus = ShowDropDownOnFocusMode.Never;
            s.Properties.ClientSideEvents.TokensChanged = "onTokensChanged";
            s.Width = Unit.Percentage(100);
            s.Height = Unit.Pixel(30);
            s.Properties.MaxLength = 50;
            s.ShowModelErrors = true;

        }).BindList(ViewData["List"]).GetHtml()
        </td>
        <td style="width:20%;">
            @Html.DevExpress().Button(s =>
        {
            s.Name = "buttonSearch";
            s.Text = @"Tìm kiếm";
            s.Images.Image.IconID = IconID.ActionsSearch16x16devav;
            s.ClientSideEvents.Click = "TimKiem";
            s.AllowFocus = false;
            s.RenderMode = ButtonRenderMode.Link;
            s.Images.Image.SpriteProperties.CssClass = "btnSearch";
            s.Images.Image.SpriteProperties.HottrackedCssClass = "btnSearchHottracked";
            s.Images.Image.SpriteProperties.PressedCssClass = "btnSearchPressed";
            s.ToolTip = "Tìm kiếm";
            s.ControlStyle.Font.Size = 13;
            s.Width = Unit.Percentage(20);
            //s.Styles.Style.HorizontalAlign = HorizontalAlign.Left;
        }).GetHtml()
        </td>
    </tr>
</table>*@
@*@Html.DevExpress().Button(
            settings =>
            {
                settings.Name = "btnLinkImageAndText";
                settings.Width = 100;
                settings.Height = 25;
                settings.RenderMode = ButtonRenderMode.Link;
                settings.Text = "Refresh";
                settings.ImagePosition = ImagePosition.Right;
                settings.Images.Image.IconID = IconID.ActionsRefresh16x16gray;
            }).GetHtml()*@

<table style="margin-top:10px">
    <tr>
        <td style="width:40%;">
            @Html.DevExpress().TokenBox(s =>
        {
            s.Properties.IncrementalFilteringMode = IncrementalFilteringMode.Contains;
            s.Name = "txt_timkiem";
            s.Properties.NullText = "Nhập từ khóa tìm kiếm theo tên ngân hàng";
            s.ControlStyle.Font.Size = 13;
            s.Properties.ShowDropDownOnFocus = ShowDropDownOnFocusMode.Never;
            s.Properties.ClientSideEvents.TokensChanged = "onTokensChanged";
            s.Width = Unit.Percentage(100);
            s.Height = Unit.Pixel(30);
            s.Properties.MaxLength = 50;
            s.ShowModelErrors = true;

        }).GetHtml()
        </td>
        <td style="padding-right: 400px">
            @Html.DevExpress().Button(s =>
        {
            s.Name = "buttonSearch";
            s.Text = "Tìm kiếm";
            s.Images.Image.IconID = IconID.ActionsSearch16x16devav;
            s.ClientSideEvents.Click = "Search";
            s.AllowFocus = false;
            s.ToolTip = "Tìm kiếm";
            s.ControlStyle.Font.Size = 13;
        }).GetHtml()
        </td>
    </tr>
</table>

Code/SourceCode/QLQ.FEW/Views/HOSO/Footer.cshtml
@Html.DevExpress().FormLayout(s =>
{
    s.Name = "FormBot";
    s.EncodeHtml = false;
    s.Width = Unit.Percentage(100); ;
    var group = s.Items.AddGroupItem(gi =>
    {
        gi.ShowCaption = DefaultBoolean.False;
        gi.HorizontalAlign = FormLayoutHorizontalAlign.Right;
        gi.ColCount = 4;
        gi.Width = Unit.Percentage(100);
        gi.GroupBoxDecoration = GroupBoxDecoration.None;

    });

    group.Items.Add(i =>
    {
        i.ShowCaption = DefaultBoolean.False;
        i.HorizontalAlign = FormLayoutHorizontalAlign.Right;
        i.Name = "btn_moi";
        i.Height = 30;
        i.NestedExtension().Button(s2 =>
        {
            s2.Width = Unit.Pixel(120);
            s2.Text = "Thêm Mới";
            s2.Height = 30;
            s2.Images.Image.Url = Url.Content("~/Content/Images/icon_them_moi.png");
            s2.ClientSideEvents.Click = "function (s, e) { btnAdd_Click(s, e); }";
        });
    });
    group.Items.Add(i =>
    {
        i.ShowCaption = DefaultBoolean.False;
        i.HorizontalAlign = FormLayoutHorizontalAlign.Right;
        i.Name = "btn_sua";
        i.Height = 30;
        i.NestedExtension().Button(s2 =>
        {
            s2.Width = Unit.Pixel(120);
            s2.Text = "Sửa";
            s2.Height = 30;
            s2.Images.Image.Url = Url.Content("~/Content/Images/icon_sua.png");
            s2.ClientSideEvents.Click = "function (s, e) { btnEdit_Click(s, e); }";
        });
    });
    group.Items.Add(i =>
    {
        i.ShowCaption = DefaultBoolean.False;
        i.HorizontalAlign = FormLayoutHorizontalAlign.Right;
        i.Name = "btn_xoa";
        i.Height = 30;
        i.NestedExtension().Button(s2 =>
        {
            s2.Width = Unit.Pixel(120);
            s2.Text = "Xóa";
            s2.Height = 30;
            s2.Images.Image.Url = Url.Content("~/Content/Images/icon_xoa.png");
            s2.ClientSideEvents.Click = "function (s, e) { btnDelete_Click(s, e); }";
        });
    });
    group.Items.Add(i =>
    {
        i.ShowCaption = DefaultBoolean.False;
        i.HorizontalAlign = FormLayoutHorizontalAlign.Right;
        i.Name = "btn_in";
        i.Height = 30;
        i.NestedExtension().Button(s2 =>
        {
            s2.Width = Unit.Pixel(120);
            s2.Text = "In Ấn";
            s2.Height = 30;
            s2.Images.Image.Url = Url.Content("~/Content/Images/in.png");
            s2.ClientSideEvents.Click = "btnInAn_Click";
        });
    });
}).GetHtml()

Code/SourceCode/QLQ.FEW/Views/HOSO/GPKDPartial.cshtml
@Html.DevExpress().Image(img =>
    {
        img.Name = "UPLOADS_GPKD";
        img.Height = Unit.Pixel(100);
        
    }).GetHtml()

Code/SourceCode/QLQ.FEW/Views/HOSO/GUQPartial.cshtml
@Html.DevExpress().Image(img =>
    {
        img.Name = "UPLOADS_GUQ";
        img.Height = Unit.Pixel(100);
        
    }).GetHtml()

Code/SourceCode/QLQ.FEW/Views/HOSO/HeadResourcesPartial.cshtml
@Html.DevExpress().GetStyleSheets(
    new StyleSheet { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
    new StyleSheet { ExtensionSuite = ExtensionSuite.GridView }
        // new StyleSheet() { ExtensionSuite = ExtensionSuite.Report }
)
@Html.DevExpress().GetScripts(
        //new Script { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
        ////new Script { ExtensionSuite = ExtensionSuite.HtmlEditor },
        //new Script { ExtensionSuite = ExtensionSuite.GridView }
)

Code/SourceCode/QLQ.FEW/Views/HOSO/Index.cshtml
@model System.Collections.IEnumerable
@{
    ViewBag.Title = "Hồ sơ pháp lý";
    Layout = "~/Views/Shared/_mainLayout.cshtml";
}

@section HeadResources{
    @Html.Partial("HeadResourcesPartial")
}

<style>
    /*style lại popup edit gridview*/
    .dxgvPopupEditForm_EIS .dxeEditArea_EIS.dxeEditAreaSys {
        height: 18px;
    }

    .dxgvPopupEditForm_EIS .dxflHALSys.dxflVATSys.dxflCaptionCell_EIS.dxflCaptionCellSys {
        vertical-align: middle;
    }

    .dxgvPopupEditForm_EIS .dxflHARSys.dxflGroupCell_EIS {
        height: 30px;
    }
    /*--------------*/
    /*style image table*/
    #gvHOSO_DXMainTable .dxgv.dx-ac img {
        height: 100px;
    }
</style>

<script type="text/javascript">

    function OnEndCallback(s, e) {
        if (s.IsNewRowEditing()) {
            var form = s.GetPopupEditForm();
            form.PopUp.AddHandler(function (s, e) {
                var editor = gvHOSO.GetEditor('NGANHANG_ID');
                editor.Focus();
            });
        }
        if (s.cpMessage != null) {
            showMessage(true, s.cpMessage);
            delete s.cpMessage;
        }

        //script ấn enter thì chuyển focus sang trường bên cạnh
        $("#gvHOSO_DXPEForm_DXEFL").find(".dxeEditAreaSys,.dxichSys,.dxbButtonSys").each(function (i, obj) {
            $(this).keypress(function (event) {
                if (event.which == 13) {
                    $("#gvHOSO_DXPEForm_DXEFL").find(".dxeEditAreaSys,.dxichSys,.dxbButtonSys").each(function (j, obj) {
                        if (j == (i + 1)) {
                            ////j nhỏ nhất bằng trường textbox cuối cùng trước khi tới checkbox
                            //if (j == 14 || j == 15 || j == 16 || j == 17) { // index checkbox
                            //    $("#gvNganHang_DXPEForm_DXEFL_DXEditor" + j + "_S").focus();
                            //} else
                            if (j == 3) { // button cập nhật
                                $("#gvHOSO_DXPEForm_DXEFL_DXCBtn0").focus();
                            } else {
                                $(this).focus();
                            }
                        }
                    });
                }
            });
        });
    }

    function btnAdd_Click(s, e) {
        ShowProgressRing();
        $.ajax({
            type: "POST",
            url: '@Url.Action("PopupSaveData", "HOSO")',
            data: {
            },
            success: function (result) {
                HideProgressRing();
                $("#popup_addnew").html(result);
            },
            failure: function () {
                HideProgressRing();
                showMessage(false, "Có lỗi xảy ra trong quá trình xử lý dữ liệu!");
            }
        });
    }

    function btnEdit_Click() {
        var index = gvHOSO.GetFocusedRowIndex();
        var key = gvHOSO.GetRowKey(index);
        ShowProgressRing();
        $.ajax({
            type: "POST",
            url: '@Url.Action("SuaHoSo", "HOSO")',
            data: {
                hosoId: key
            },
            success: function (result) {
                HideProgressRing();
                if (result == "Fail") {
                    showMessage(false, "Có lỗi xảy ra trong quá trình xử lý dữ liệu!");
                    return;
                }
                $("#popup_addnew").html(result);
            },
            failure: function () {
                HideProgressRing();
                showMessage(false, "Có lỗi xảy ra trong quá trình xử lý dữ liệu!");
            }
        });
    }

    function ctrUpload_DLNH_FileUploadComplete(s, e) {
        if (e.isValid) {
            UPLOADS_DLNH.SetImageUrl("../../" + e.callbackData);
        }
    }

    function ctrUpload_GPKD_FileUploadComplete(s, e) {
        if (e.isValid) {
            UPLOADS_GPKD.SetImageUrl("../../" + e.callbackData);
        }
    }

    function ctrUpload_GUQ_FileUploadComplete(s, e) {
        if (e.isValid) {
            UPLOADS_GUQ.SetImageUrl("../../" + e.callbackData);

            //var fileName = e.callbackData.split('/').pop();
            //$("#GUQ_hidden").val(fileName);
        }
    }

    function ctrUpload_BCTC_FileUploadComplete(s, e) {
        if (e.isValid) {
            UPLOADS_BCTC.SetImageUrl("../../" + e.callbackData);
        }
    }

    function btnLuu_Click() {

        var dlnh = UPLOADS_DLNH.GetValue();
        if (dlnh != null) {
            dlnh = dlnh.split('/').pop();
        }
        var gpkd = UPLOADS_GPKD.GetValue();
        if (gpkd != null) {
            gpkd = gpkd.split('/').pop();
        }
        var guq = UPLOADS_GUQ.GetValue();
        if (guq != null) {
            guq = guq.split('/').pop();
        }
        var bctc = UPLOADS_BCTC.GetValue();
        if (bctc != null) {
            bctc = bctc.split('/').pop();
        }

        var formHoSo = $('#form-hoso');
        if (formHoSo.valid()) {
            //ShowprogressRing();
            $.ajax({
                cache: false,
                async: true,
                type: "POST",
                url: '@Url.Action("LuuHoSo", "HOSO")',
                data: formHoSo.serialize() + "&DLNH=" + dlnh + "&GPKD=" + gpkd + "&GUQ=" + guq + "&BCTC=" + bctc,
                success: function (data) {
                    //HideprogressRing();
                    if (data == "Success") {
                        showMessage(true, "Lưu thành công");
                        gvHOSO.PerformCallback();
                        $("#popup_addnew").hide();
                    } else {
                        showMessage(false, "Có lỗi xảy ra trong quá trình lưu dữ liệu");
                    }
                },
                failure: function () {
                    //HideprogressRing();
                    showMessage(false, "Có lỗi xảy ra trong quá trình lưu dữ liệu");
                }
            });
        }
    }

    function btnDelete_Click(s, e) {
        var index = gvHOSO.GetFocusedRowIndex();
        if (index == null || index == -1) {
            showMessage(false, "vui lòng chọn 1 bản ghi !");
            return;
        }
        $("#popup_Delete_Confirm").val('ConfirmDeleteHOSO');
        window.popup_Delete.Show();
    }

    function ConfirmDeleteHOSO() {
        var index = gvHOSO.GetFocusedRowIndex();
        gvHOSO.DeleteRow(index);
    }

    function btnInAn_Click() {

        @*$.ajax({
            cache: false,
            async: true,
            type: "POST",
            url: '@Url.Action("InAn", "HOSO")',
            data: {

            },
            success: function (data) {
                //HideprogressRing();
                if (data == "Success") {
                    showMessage(true, "Lưu thành công");
                    gvHOSO.PerformCallback();
                } else {
                    showMessage(false, "Có lỗi xảy ra trong quá trình lưu dữ liệu");
                }
            },
            failure: function () {
                //HideprogressRing();
                showMessage(false, "Có lỗi xảy ra trong quá trình lưu dữ liệu");
            }
        });*@
    }

    function showMessage(isSucess, text) {
        if (isSucess) {
            $('#noidung_success').text(text.toString());
            window.Message_Success.Show();
            setTimeout(function () { Message_Success.Hide(); }, 2000);
        }
        else {
            $('#noidung').text(text.toString());
            window.Message.Show();
        }
    }

    function ShowProgressRing() {
        window.LoadingPanel.Show();
    }

    function HideProgressRing() {
        window.LoadingPanel.Hide();
    }

</script>
@using (Html.BeginForm())
{
    <div>
        <div>
            <ul class="ul-tieude">
                <li>
                    <span>Hồ sơ pháp lý</span>
                </li>
            </ul>
        </div>
        <div class="col-xs-12 text-right btn-span" id="demo">
            <div class="img-span" style="padding-bottom:18px"><img src="~/Content/Images/icon_mo_rong.png" /></div>
        </div>
        <div class="col-sm-12 none-padding chitiet" style="padding-bottom:15px">
            @*@Html.Partial("FilterView")*@
        </div>
    </div>
    <div id="HOSOPartial_div">
        @Html.Action("HOSOPartial")
    </div>
    <div class="col-sm-12 none-padding footer">
        <div class="btm-toolbar">
            @Html.Partial("Footer")
        </div>
    </div>
    <div id="popup_addnew"></div>
}

@Html.Partial("_Message")
@Html.Partial("_MessageSuccess")
@Html.Partial("PopupConfirmDelete")
@Html.Partial("LoadingPanel")

Code/SourceCode/QLQ.FEW/Views/HOSO/PopupSaveData.cshtml
@model QLQ.Core.Domain.HOSO
@Html.DevExpress().PopupControl(
    settings =>
    {
        settings.Name = "Popup_HoSo";
        settings.Width = 800;
        settings.Height = 650;
        settings.ShowOnPageLoad = true;
        settings.AllowDragging = false;
        settings.CloseAction = CloseAction.CloseButton;
        settings.CloseOnEscape = true;
        settings.PopupAnimationType = AnimationType.None;
        settings.ShowHeader = true;
        settings.Modal = true;
        settings.ScrollBars = System.Web.UI.WebControls.ScrollBars.Auto;
        settings.HeaderText = "HỒ SƠ";
        settings.ShowCloseButton = true;
        settings.PopupHorizontalAlign = PopupHorizontalAlign.WindowCenter;
        settings.PopupVerticalAlign = PopupVerticalAlign.WindowCenter;
        //settings.ClientSideEvents.Init = "Popup_UyNhiemChi_Init";
        settings.SetContent(() =>
        {

            Html.RenderPartial("FormAdd", Model);

        });
    }).GetHtml()


@Html.DevExpress().LoadingPanel(
                settings =>
                {
                    settings.Name = "LoadingPanel_HoSo";

                    settings.Modal = true;
                    //settings.ContainerElementID = "popup_result";

                }
            ).GetHtml()