Code/SourceCode/QLQ.FEW/Controllers/SoChiTietTienLaiDauTuQuyBHXHController.cs
using FX.Core;
using QLQ.Core.CustomView;
using QLQ.Core.IService;
using QLQ.Core.Security;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace QLQ.FEW.Controllers
{
    [Function(QlqFunctions.SOCHTIETLAIDAUTUQUYBHXH)]
    [Authorize]
    public class SoChiTietTienLaiDauTuQuyBHXHController : BaseController
    {
        private readonly ILAISUATNH_DTLService _iLaiSuatNhDtlService;
        private readonly ILAISUATNH_HDRService _iLaiSuatNhHdrService;
        private readonly IHopDongService _iHopDongService;
        //
        // GET: /SoTheoDoi/
        public SoChiTietTienLaiDauTuQuyBHXHController()
        {
            _iLaiSuatNhDtlService = IoC.Resolve<ILAISUATNH_DTLService>();
            _iLaiSuatNhHdrService = IoC.Resolve<ILAISUATNH_HDRService>();
            _iHopDongService = IoC.Resolve<IHopDongService>();
        }

        [ActionPermissions(QlqActions.VIEW)]
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult SoChiTietTienLaiDauTuQuyBHXHPartial()
        {
            ViewBag.ListHopdong = _iHopDongService.GetAll();
            return PartialView("SoChiTietTienLaiDauTuQuyBHXHPartial");
        }

        [HttpPost]
        [ActionPermissions(QlqActions.PRINT)]
        public ActionResult fn_InAn(int? sohopdong/*,string tendonvi,  int? thoihanvay, DateTime? ngayhd, decimal? laisuat*/)
        {

            List<SoChiTietTienLaiDauTuBHXHModel> lst = new List<SoChiTietTienLaiDauTuBHXHModel> {
            new SoChiTietTienLaiDauTuBHXHModel() {
                ngay_ghiso = DateTime.Now.Date,
                soct = 1, ngay_ct = DateTime.Now.Date,
                diengiai = "xxx", tienvay = 1231212312,
                laisuat = "5%", songaytinhlai = 365,
                phaithu =213123,dathu=1231,cl=434
            } };

            SoChiTietLaiDauTuQuyBHXH_Report report = new SoChiTietLaiDauTuQuyBHXH_Report();
            report.DataSource = lst;
            return PartialView("ReportSoChiTietTienLaiDauTuQuyBHXH", report);
        }

    }
}

Code/SourceCode/QLQ.FEW/Views/SoChiTietTienLaiDauTuQuyBHXH/HeadResourcesPartial.cshtml
@Html.DevExpress().GetStyleSheets(
    new StyleSheet { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
    new StyleSheet { ExtensionSuite = ExtensionSuite.GridView },
    new StyleSheet() { ExtensionSuite = ExtensionSuite.Report }
   
)
@Html.DevExpress().GetScripts(
        //new Script { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
        ////new Script { ExtensionSuite = ExtensionSuite.HtmlEditor },
        //new Script { ExtensionSuite = ExtensionSuite.GridView }
)

Code/SourceCode/QLQ.FEW/Views/SoChiTietTienLaiDauTuQuyBHXH/Index.cshtml
@{
    ViewBag.Title = "Số chi tiết tiền lãi đầu tư quỹ BHXH";
    Layout = "~/Views/Shared/_mainLayout.cshtml";
}

@section HeadResources{
    @Html.Partial("HeadResourcesPartial")
}
<script>
    function btn_InAnClick() {
        var sohopdong = cbb_Hopdong.GetValue();
        //var ThoiGian = date_HieuLuc.GetValue();
        //var loai = cbb_loaiLS.GetValue();
        //var type = cbb_type.GetValue();
        LoadingPanel.Show();
        $.ajax({
            type: "POST",
            url: '@Url.Action("fn_InAn", "SoChiTietTienLaiDauTuQuyBHXH")',
            data: {
                sohopdong: sohopdong
                //year: ThoiGian,
                //CN_TC: loai,
                //type: type
            }
        }).done(function (result) {
            LoadingPanel.Hide();
            $("#SoChiTietTienLaiDauTu_Report").html(result);
        });
    }
</script>
<div id="gridview" style="width:60%; margin:auto;">
    @Html.Action("SoChiTietTienLaiDauTuQuyBHXHPartial")
</div>
@Html.Partial("_Message")
@Html.Partial("_MessageSuccess")
@Html.Partial("LoadingPanel")
<div id="SoChiTietTienLaiDauTu_Report"></div>

Code/SourceCode/QLQ.FEW/Views/SoChiTietTienLaiDauTuQuyBHXH/ReportSoChiTietTienLaiDauTuQuyBHXH.cshtml
<style type="text/css">
    .dx-overlay-wrapper {
        z-index: 100000 !important;
    }
</style>
<script type="text/javascript">
    function OnInit(s, e) {
        //var nodeKey = window.TreeList_NhomICD.GetFocusedNodeKey();
        //  window.popupReport19.PerformCallback();
        AdjustSize();
        ASPxClientUtils.AttachEventToElement(window, "resize", function (evt) {
            AdjustSize();
        });
    }
    function OnEndCallback(s, e) {
        AdjustSize();
    }
    function AdjustSize() {
        window.MauS12_H_Report.SetWidth(document.documentElement.clientWidth);
        window.MauS12_H_Report.SetHeight(document.documentElement.clientHeight);

    }
</script>
@model DevExpress.XtraReports.UI.XtraReport
@*// chỉ cần khai báo lớp cha*@
@Html.DevExpress().PopupControl(
    settings =>
    {
        settings.Name = "SCTTLDTQBHXHReport";
        settings.ClientSideEvents.PopUp = "function(s, e) { s.SetWidth(document.documentElement.clientWidth); s.SetHeight(document.documentElement.clientHeight); }";
        settings.ShowOnPageLoad = true;
        settings.AllowDragging = false;
        settings.CloseAction = CloseAction.CloseButton;
        settings.CloseOnEscape = true;
        settings.PopupAnimationType = AnimationType.None;
        settings.ShowHeader = true;
        settings.Modal = true;
        settings.ScrollBars = System.Web.UI.WebControls.ScrollBars.Auto;
        settings.HeaderText = "Số chi tiết";
        settings.ShowCloseButton = true;
        settings.PopupHorizontalAlign = PopupHorizontalAlign.LeftSides;
        settings.PopupVerticalAlign = PopupVerticalAlign.TopSides;
        settings.SetContent(() =>
        {
            @Html.DevExpress().WebDocumentViewer(poper => //khai báo đối tượng nặc danh sử dụng luôn
                        {

                            poper.Name = "SCTTLDTQBHXH";


                        }).Bind(Model).GetHtml();
        });
    }).GetHtml()

Code/SourceCode/QLQ.FEW/Views/SoChiTietTienLaiDauTuQuyBHXH/SoChiTietTienLaiDauTuQuyBHXHPartial.cshtml
@Html.DevExpress().PopupControl(
    settings =>
    {
        settings.Name = "ModalSoChiTiet";
        settings.Width = 530;
        settings.HeaderText = "Sổ chi tiết tiền lãi đầu tư quỹ BHXH";
        settings.Modal = true;
        settings.ShowCloseButton = false;
        settings.AllowDragging = false;
        settings.CloseAction = CloseAction.None;
        settings.ShowOnPageLoad = true;
        settings.PopupHorizontalAlign = PopupHorizontalAlign.WindowCenter;
        settings.PopupVerticalAlign = PopupVerticalAlign.WindowCenter;

        settings.SetContent(() =>
        {
            ViewContext.Writer.Write("<table style='margin:20px;'><tr><td style='line-height:25px; padding-left:20px; width:100px;'><b>Ngân hàng:</b></td><td>");
            Html.DevExpress().ComboBox(cb =>
            {
                cb.Name = "cbb_Hopdong";
                cb.Width = 150;
                cb.SelectedIndex = 0;
                cb.Properties.IncrementalFilteringMode = IncrementalFilteringMode.StartsWith;
                cb.Properties.DropDownStyle = DropDownStyle.DropDown;
                cb.Properties.TextField = "so_hopdong";
                cb.Properties.ValueField = "hopdong_id";
            }).BindList(ViewBag.ListHopdong).GetHtml();

            //ViewContext.Writer.Write("</td><td></td></tr><tr><td style='line-height:25px; padding-left:20px; '><b>Thời gian:</b></td><td>");
            //Html.DevExpress().ComboBox(cb =>
            //{
            //    cb.Name = "date_HieuLuc";
            //    cb.Width = 150;
            //    cb.SelectedIndex = 0;
            //    cb.Properties.IncrementalFilteringMode = IncrementalFilteringMode.StartsWith;
            //    cb.Properties.DropDownStyle = DropDownStyle.DropDown;
            //    int i;
            //    for (i = DateTime.Now.Year; i >= 2000; i--)
            //    {
            //        cb.Properties.Items.Add(i.ToString(), i);
            //    }
            //}).GetHtml();
            //ViewContext.Writer.Write("</td><td></td></tr><tr><td style='line-height:25px; padding-left:20px;'><b>Loại lãi suất:</b></td><td>");
            //Html.DevExpress().ComboBox(cb =>
            //{
            //    cb.Name = "cbb_loaiLS";
            //    cb.Width = 150;
            //    cb.SelectedIndex = 0;
            //    cb.Properties.IncrementalFilteringMode = IncrementalFilteringMode.StartsWith;
            //    cb.Properties.DropDownStyle = DropDownStyle.DropDown;
            //    cb.Properties.Items.Add("Lãi suất cá nhân", 0);
            //    cb.Properties.Items.Add("Lãi suất tổ chức", 1);
            //}).GetHtml();

            //ViewContext.Writer.Write("</td><td style='padding-left:20px;'>");

            //Html.DevExpress().ComboBox(cb =>
            //{
            //    cb.Name = "cbb_type";
            //    cb.Width = 150;
            //    cb.SelectedIndex = 0;
            //    cb.Properties.IncrementalFilteringMode = IncrementalFilteringMode.StartsWith;
            //    cb.Properties.DropDownStyle = DropDownStyle.DropDown;
            //    cb.Properties.Items.Add("Lãi suất cuối kì", 0);
            //    cb.Properties.Items.Add("Lãi suất hàng tháng", 1);
            //}).GetHtml();

            ViewContext.Writer.Write("</td></tr><tr><td colspan='3' style='text-align:center; padding-top:15px;'>");
            Html.DevExpress().Button(
                buttonSettings =>
                {
                    buttonSettings.Name = "btn_InAn";
                    buttonSettings.ControlStyle.CssClass = "button";
                    buttonSettings.Width = 100;
                    buttonSettings.Text = "In ấn";
                    buttonSettings.UseSubmitBehavior = true;
                    buttonSettings.ClientSideEvents.Click = "btn_InAnClick";
                }
            )
            .Render();
            ViewContext.Writer.Write(" &nbsp; &nbsp;");
            Html.DevExpress().Button(
                    buttonSettings =>
                    {
                        buttonSettings.Name = "btnCancel";
                        buttonSettings.ControlStyle.CssClass = "button";
                        buttonSettings.Width = 80;
                        buttonSettings.Text = "Hủy";
                        buttonSettings.ClientSideEvents.Click = "function(s, e){ window.location.href='/' }";
                    }
                )
                .Render();
            ViewContext.Writer.Write("</td></tr></table>");
        });
    }).GetHtml()